version: '3.4'

services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd12345!
    ports:
      - "1433:1433"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      DBServer: sql-server    
    depends_on:
      - sql-server
